/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java.NBT;

import static org.junit.Assert.assertEquals;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.StringWriter;

import org.junit.Test;

import nbt.NBTCompound;
import nbt.NBTList;
import nbt.NBTType;
import nbt.NbtReader;
import nbt.NbtWriter;
import nbt.StringNbtWriter;

public class LibraryTest {
    
    private static final String EXPECTED_STRING = "{s:\"A string\",COMP1:{keyn1:\"NESTED1\",COMP2:{keyn2:\"NESTED2\"}},\"Some int\":123,testList:[\"Gurke1\",\"Gurke2\",\"Gurke3\"],byte:12b,short:123s,int:1234,long:12345l,float:0.1f,double:0.01d}";
    
    @Test
    public void bigtest1() throws Exception {
        NBTCompound test = new NBTCompound();
        test.putString("s", "A string");
        NBTCompound nested = new NBTCompound();
        nested.putString("keyn1", "NESTED1");
        test.putCompound("COMP1", nested);
        test.putInt("Some int", 123);
        NBTCompound nested2 = new NBTCompound();
        nested2.putString("keyn2", "NESTED2");
        nested.putCompound("COMP2", nested2);
        NBTList list = new NBTList(NBTType.String);
        list.add("Gurke1");
        list.add("Gurke2");
        list.add("Gurke3");
        test.putList("testList", list);
        test.putByte("byte", (byte) 12);
        test.putShort("short", (short) 123);
        test.putInt("int", 1234);
        test.putLong("long", 12345l);
        test.putFloat("float", 0.1f);
        test.putDouble("double", 0.01);
        try (NbtWriter writer = new NbtWriter(new FileOutputStream("tmp.dat"))) {
            test.accept(writer);
        }
        NBTCompound comp;
        try (NbtReader reader = new NbtReader(new FileInputStream("tmp.dat"))) {
            comp = reader.toCompoundTag();
        }
        try (StringWriter writ = new StringWriter()) {
            StringNbtWriter sw = new StringNbtWriter(writ);
            comp.accept(sw);
            assertEquals(EXPECTED_STRING, writ.toString());
        }
    }
}
